stargate:
  graphql:
    # Whether to default to the oldest keyspace when the user accesses /graphql.
    # If this is disabled, /graphql throws an error, and the keyspace must be provided explicitly in
    # the path, as in /graphql/ksName.
    enable-default-keyspace: true

    # Whether to expose the GraphQL Playground in-browser IDE at /playground.
    enable-playground: true

quarkus:
  grpc:
    clients:
      bridge:
        host: localhost
        port: 8091
